// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js auto-loads .env.local for the app itself, but the Prisma CLI's
// own dotenv import only reads .env by default — load .env.local explicitly
// so `prisma migrate`/`db seed` see the same DATABASE_URL/DIRECT_URL.
config({ path: ".env.local" });

// The CLI (migrate/db push/introspect) needs a direct, non-pooled connection
// — DDL statements don't work reliably through PgBouncer's transaction mode,
// which is what DATABASE_URL points at. DIRECT_URL is Render's direct
// connection string; the app's runtime PrismaClient (src/lib/db.ts) uses
// DATABASE_URL (pooled) instead, via a driver adapter.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
